/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calculator_JNI */

#ifndef _Included_calculator_JNI
#define _Included_calculator_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calculator_JNI
 * Method:    sum
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_calculator_1JNI_sum
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     calculator_JNI
 * Method:    odd
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_calculator_1JNI_odd
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     calculator_JNI
 * Method:    mul
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_calculator_1JNI_mul
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     calculator_JNI
 * Method:    div
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_calculator_1JNI_div
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     calculator_JNI
 * Method:    integerDiv
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_calculator_1JNI_integerDiv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     calculator_JNI
 * Method:    modulo
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_calculator_1JNI_modulo
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
