/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calcm_jni_calcm_JNI */

#ifndef _Included_calcm_jni_calcm_JNI
#define _Included_calcm_jni_calcm_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calcm_jni_calcm_JNI
 * Method:    info
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_calcm_1jni_calcm_1JNI_info
  (JNIEnv *, jobject);

/*
 * Class:     calcm_jni_calcm_JNI
 * Method:    mtx_mul
 * Signature: (Lmgui/mgui;)V
 */
JNIEXPORT void JNICALL Java_calcm_1jni_calcm_1JNI_mtx_1mul
  (JNIEnv *, jobject, jobject);

/*
 * Class:     calcm_jni_calcm_JNI
 * Method:    mtx_add
 * Signature: (Lmgui/mgui;)V
 */
JNIEXPORT void JNICALL Java_calcm_1jni_calcm_1JNI_mtx_1add
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
